import { FOOTER_LINKS, PRODUCTS, SERVICE_STATS, TEAM_MEMBERS, type FooterLinkGroup, type Product, type ServiceStat, type TeamMember } from "@/lib/data";

export type Locale = "en" | "de";

export const LOCALES: Locale[] = ["en", "de"];

export function isLocale(value: string): value is Locale {
  return LOCALES.includes(value as Locale);
}

export function localizePath(locale: Locale, path: string): string {
  return locale === "en" ? `/en${path === "/" ? "" : path}` : `/de${path === "/" ? "" : path}`;
}

export interface SiteMessages {
  nav: { home: string; products: string; about: string; contact: string; contactUs: string; productLabel: string; openMenu: string; closeMenu: string };
  hero: { badge: string; title: string; accent: string; text: string; consultation: string; explore: string; liveOverview: string; online: string; efficiency: string; peakDemand: string; co2: string };
  features: { eyebrow: string; title: string; items: { title: string; text: string }[] };
  products: { eyebrow: string; heading: string; viewAll: string; platform: string };
  about: { eyebrow: string; title: string; text: string; careers: string; careersTitle: string; careersText: string; careersCta: string; teamEyebrow: string; teamTitle: string };
  contact: { eyebrow: string; title: string; text: string };
  cta: { eyebrow: string; title: string; text: string; button: string };
  footer: { company: string; products: string; legal: string; brand: string; careers: string; privacy: string; terms: string; cookies: string; copyright: string; tagline: string };
  legal: { eyebrow: string; updated: string; privacyTitle: string; privacy: string[]; termsTitle: string; terms: string[]; cookiesTitle: string; cookies: string[] };
  metadata: { homeTitle: string; homeDescription: string; productsTitle: string; productsDescription: string; aboutTitle: string; aboutDescription: string; contactTitle: string; contactDescription: string; privacyDescription: string; termsDescription: string; cookiesDescription: string };
}

const EN: SiteMessages = {
  nav: { home: "Home", products: "Products", about: "About", contact: "Contact", contactUs: "Contact Us", productLabel: "Products", openMenu: "Open navigation menu", closeMenu: "Close navigation menu" },
  hero: { badge: "Industrial energy intelligence", title: "Make every", accent: "watt count.", text: "Apollo turns complex industrial energy systems into measurable, actionable performance. Monitor, optimise, and decarbonise from one intelligent platform.", consultation: "Book a consultation", explore: "Explore platform", liveOverview: "Live site overview", online: "Online", efficiency: "Energy efficiency", peakDemand: "Peak demand", co2: "CO₂ avoided" },
  features: { eyebrow: "The Apollo approach", title: "Operational clarity at every scale.", items: [{ title: "See the system", text: "One live view across meters, assets, storage, and production operations." }, { title: "Act at the edge", text: "Fast control loops respond to demand and anomalies before they become downtime." }, { title: "Prove the outcome", text: "Board-ready reporting connects every intervention to cost and carbon impact." }, { title: "Build resilience", text: "Modernise existing infrastructure while progressing toward a lower-carbon future." }] },
  products: { eyebrow: "The platform", heading: "Built for the real world.", viewAll: "View all products", platform: "The platform" },
  about: { eyebrow: "About Apollo", title: "Energy progress, made practical.", text: "We combine industrial engineering, intelligent software, and sustainability expertise to help teams make better decisions with the energy systems they already have.", careers: "Careers", careersTitle: "Help build a more resilient energy future.", careersText: "We are growing a team that cares about practical engineering, measurable outcomes, and the people who rely on critical infrastructure.", careersCta: "Start a conversation", teamEyebrow: "People behind the platform", teamTitle: "Engineering with purpose." },
  contact: { eyebrow: "Contact Apollo", title: "Let's find your next move.", text: "Share a little about your site and your goals. Our team will come back with a focused first conversation." },
  cta: { eyebrow: "Start with one conversation", title: "Ready to make energy a competitive advantage?", text: "Tell us where you are today. We will map the clearest next move for your site, your team, and your targets.", button: "Talk to Apollo" },
  footer: { company: "Company", products: "Products", legal: "Legal", brand: "Industrial-grade energy intelligence for a decarbonised economy.", careers: "Careers", privacy: "Privacy Policy", terms: "Terms of Service", cookies: "Cookie Policy", copyright: "All rights reserved.", tagline: "Built for a zero-carbon industrial future." },
  legal: { eyebrow: "Legal", updated: "Last updated: September 23, 2026", privacyTitle: "Privacy Policy", privacy: ["Apollo Green Solutions respects your privacy. This policy explains what information we collect when you use our website or contact our team, and how we use it to provide and improve our services.", "We may collect contact details, company information, and the contents of enquiries you submit. We use this information to respond to requests, provide relevant proposals, maintain site security, and meet our legal obligations.", "We do not sell personal information. We may share information with service providers who help us operate the website and communications, subject to appropriate confidentiality and security commitments.", "You may ask us to access, correct, or delete your personal information by contacting us through the contact page."], termsTitle: "Terms of Service", terms: ["These terms govern your use of the Apollo Green Solutions website. By accessing the site, you agree to use it lawfully and in a way that does not interfere with its operation or security.", "Website content is provided for general information about our products and services. It is not a substitute for site-specific engineering, financial, legal, or regulatory advice.", "You may not copy, misuse, or attempt to reverse engineer the site or its content without our written permission.", "To ask a question about these terms or our services, please contact the Apollo Green Solutions team through the contact page."], cookiesTitle: "Cookie Policy", cookies: ["Cookies are small text files stored on your device when you visit a website. Apollo Green Solutions uses limited cookies and similar technologies to keep the site secure and understand basic website performance.", "Essential cookies are needed for parts of the website to function. Optional analytics tools, where enabled, are used to improve the experience.", "You can manage or remove cookies through your browser settings. Disabling some cookies may affect certain website features.", "We may update this policy when our website or service providers change."] },
  metadata: { homeTitle: "Industrial energy intelligence", homeDescription: "Monitor, optimise, and decarbonise industrial energy systems with Apollo.", productsTitle: "Products", productsDescription: "Explore Apollo's energy monitoring, storage, retrofit, and carbon reporting products.", aboutTitle: "About", aboutDescription: "Meet the people building practical energy intelligence at Apollo Green Solutions.", contactTitle: "Contact", contactDescription: "Start a conversation about your site's energy performance.", privacyDescription: "Learn how Apollo Green Solutions collects, uses, and protects personal information.", termsDescription: "Review the terms that govern use of the Apollo Green Solutions website.", cookiesDescription: "Understand how Apollo Green Solutions uses cookies and similar technologies." },
};

const DE: SiteMessages = {
  nav: { home: "Startseite", products: "Produkte", about: "Über uns", contact: "Kontakt", contactUs: "Kontakt aufnehmen", productLabel: "Produkte", openMenu: "Navigationsmenü öffnen", closeMenu: "Navigationsmenü schließen" },
  hero: { badge: "Intelligente Energie für die Industrie", title: "Jede", accent: "Wattstunde zählt.", text: "Apollo verwandelt komplexe industrielle Energiesysteme in messbare, umsetzbare Leistung. Überwachen, optimieren und dekarbonisieren Sie Ihre Anlagen mit einer intelligenten Plattform.", consultation: "Beratung buchen", explore: "Plattform entdecken", liveOverview: "Live-Übersicht", online: "Online", efficiency: "Energieeffizienz", peakDemand: "Lastspitzen", co2: "CO₂ vermieden" },
  features: { eyebrow: "Der Apollo-Ansatz", title: "Klarheit im Betrieb, auf jeder Ebene.", items: [{ title: "Das System verstehen", text: "Eine Live-Sicht auf Zähler, Anlagen, Speicher und Produktionsabläufe." }, { title: "Direkt handeln", text: "Schnelle Regelkreise reagieren auf Lasten und Anomalien, bevor Ausfälle entstehen." }, { title: "Ergebnisse belegen", text: "Berichte für Entscheider verbinden jede Maßnahme mit Kosten- und CO₂-Wirkung." }, { title: "Resilienz aufbauen", text: "Bestehende Infrastruktur modernisieren und gleichzeitig den CO₂-Fußabdruck senken." }] },
  products: { eyebrow: "Die Plattform", heading: "Für die echte Industrie entwickelt.", viewAll: "Alle Produkte ansehen", platform: "Die Plattform" },
  about: { eyebrow: "Über Apollo", title: "Energiefortschritt, praktisch umgesetzt.", text: "Wir verbinden industrielle Ingenieurskunst, intelligente Software und Nachhaltigkeitsexpertise, damit Teams mit ihren bestehenden Energiesystemen bessere Entscheidungen treffen.", careers: "Karriere", careersTitle: "Gestalten Sie die resiliente Energiezukunft mit.", careersText: "Wir bauen ein Team für praxisnahe Technik, messbare Ergebnisse und die Menschen, die auf kritische Infrastruktur angewiesen sind.", careersCta: "Gespräch beginnen", teamEyebrow: "Menschen hinter der Plattform", teamTitle: "Ingenieurskunst mit Verantwortung." },
  contact: { eyebrow: "Apollo kontaktieren", title: "Lassen Sie uns den nächsten Schritt finden.", text: "Erzählen Sie uns etwas über Ihren Standort und Ihre Ziele. Unser Team meldet sich mit einem fokussierten ersten Gespräch." },
  cta: { eyebrow: "Beginnen wir mit einem Gespräch", title: "Soll Energie zum Wettbewerbsvorteil werden?", text: "Beschreiben Sie uns Ihre Ausgangslage. Wir zeigen den klarsten nächsten Schritt für Standort, Team und Ziele.", button: "Mit Apollo sprechen" },
  footer: { company: "Unternehmen", products: "Produkte", legal: "Rechtliches", brand: "Industrietaugliche Energieintelligenz für eine dekarbonisierte Wirtschaft.", careers: "Karriere", privacy: "Datenschutz", terms: "Nutzungsbedingungen", cookies: "Cookie-Richtlinie", copyright: "Alle Rechte vorbehalten.", tagline: "Für eine industrielle Zukunft ohne CO₂." },
  legal: { eyebrow: "Rechtliches", updated: "Zuletzt aktualisiert: 23. September 2026", privacyTitle: "Datenschutz", privacy: ["Apollo Green Solutions nimmt den Schutz Ihrer Daten ernst. Diese Richtlinie erläutert, welche Informationen wir bei der Nutzung unserer Website oder bei einer Kontaktaufnahme erheben und wie wir sie verwenden.", "Wir können Kontaktdaten, Unternehmensangaben und den Inhalt Ihrer Anfrage erfassen. Wir nutzen diese Informationen, um Anfragen zu beantworten, passende Vorschläge zu erstellen, die Website zu sichern und gesetzliche Pflichten zu erfüllen.", "Wir verkaufen keine personenbezogenen Daten. Eine Weitergabe an Dienstleister erfolgt nur, wenn sie uns beim Betrieb der Website oder Kommunikation unterstützen und angemessenen Vertraulichkeits- und Sicherheitsanforderungen unterliegen.", "Sie können Auskunft, Berichtigung oder Löschung Ihrer Daten über unsere Kontaktseite anfragen."], termsTitle: "Nutzungsbedingungen", terms: ["Diese Bedingungen regeln die Nutzung der Website von Apollo Green Solutions. Mit dem Zugriff verpflichten Sie sich zu einer rechtmäßigen Nutzung, die Betrieb und Sicherheit der Website nicht beeinträchtigt.", "Die Inhalte dienen der allgemeinen Information über unsere Produkte und Leistungen. Sie ersetzen keine standortbezogene technische, finanzielle, rechtliche oder regulatorische Beratung.", "Ohne unsere schriftliche Zustimmung dürfen Sie Inhalte nicht kopieren, missbrauchen oder versuchen, die Website zurückzuentwickeln.", "Fragen zu diesen Bedingungen oder unseren Leistungen beantwortet das Apollo-Team über die Kontaktseite."], cookiesTitle: "Cookie-Richtlinie", cookies: ["Cookies sind kleine Textdateien, die beim Besuch einer Website auf Ihrem Gerät gespeichert werden. Apollo Green Solutions verwendet wenige Cookies und ähnliche Technologien, um die Website sicher zu betreiben und ihre grundlegende Leistung zu verstehen.", "Notwendige Cookies ermöglichen bestimmte Funktionen. Optionale Analysetools werden, sofern aktiviert, zur Verbesserung der Nutzererfahrung eingesetzt.", "Sie können Cookies über die Einstellungen Ihres Browsers verwalten oder löschen. Bei einer Deaktivierung können einzelne Funktionen eingeschränkt sein.", "Wir aktualisieren diese Richtlinie, wenn sich Website oder Dienstleister ändern."] },
  metadata: { homeTitle: "Intelligente Energie für die Industrie", homeDescription: "Industrielle Energiesysteme mit Apollo überwachen, optimieren und dekarbonisieren.", productsTitle: "Produkte", productsDescription: "Entdecken Sie Apollos Lösungen für Energiemonitoring, Speicher, Retrofit und CO₂-Berichte.", aboutTitle: "Über uns", aboutDescription: "Lernen Sie das Team hinter der praxisnahen Energieintelligenz von Apollo Green Solutions kennen.", contactTitle: "Kontakt", contactDescription: "Starten Sie ein Gespräch über die Energieperformance Ihres Standorts.", privacyDescription: "Erfahren Sie, wie Apollo Green Solutions personenbezogene Daten erhebt, nutzt und schützt.", termsDescription: "Lesen Sie die Bedingungen für die Nutzung der Website von Apollo Green Solutions.", cookiesDescription: "Erfahren Sie, wie Apollo Green Solutions Cookies und ähnliche Technologien verwendet." },
};

const GERMAN_PRODUCTS: Product[] = [
  { ...PRODUCTS[0], tagline: "Energieintelligenz in Echtzeit", description: "Industrielles Sensornetz für Telemetrie im Sekundenbruchteil von Transformatoren, Motoren, HLK und Produktionslinien. Edge-ML erkennt Anomalien, bevor sie zu Ausfällen führen." },
  { ...PRODUCTS[1], tagline: "Optimierung von Batteriespeichern", description: "KI-gestützte Batteriespeicher senken Lastspitzenkosten um bis zu 40 %, sichern die USV-Versorgung und nutzen automatisch Systemdienst-Erlöse. Vollständig mit GridSense für geschlossene Regelkreise integriert." },
  { ...PRODUCTS[2], tagline: "Modernisieren statt ersetzen", description: "Verlängern Sie die Lebensdauer und Intelligenz bestehender Industrieanlagen mit nicht-invasiven Hardware- und Firmware-Upgrades. So werden Effizienzgewinne von 20–35 % ohne teuren Austausch möglich." },
  { ...PRODUCTS[3], tagline: "Nachhaltigkeits- und CO₂-Berichte", description: "Automatisierte Erfassung der Scope-1-, 2- und 3-Emissionen nach GHG Protocol mit entscheidungsreifen PDF- und API-Berichten für ESG, ISO 14064 und CSRD." },
];

const GERMAN_TEAM: TeamMember[] = [
  { ...TEAM_MEMBERS[0], role: "Chief Executive Officer", bio: "Als ehemalige Architektin für Energiesysteme bei Siemens Smart Infrastructure entwarf Elif zwölf Jahre lang netzweite Automatisierung. 2019 gründete sie Apollo Green Solutions." },
  { ...TEAM_MEMBERS[1], role: "Chief Technology Officer", bio: "Marcus promovierte in Leistungselektronik an der TU Delft. Er leitet Hardware- und Firmware-Entwicklung und hält sieben Patente für Batteriesysteme und Edge-Architekturen." },
  { ...TEAM_MEMBERS[2], role: "Leitung Nachhaltigkeit", bio: "Lena ist zertifizierte GHG-Prüferin und ehemalige ESG-Analystin bei KPMG. Sie entwickelt CarbonLens und berät zu CSRD und wissenschaftsbasierten Zielen." },
  { ...TEAM_MEMBERS[3], role: "VP Engineering", bio: "Als ehemaliger Bosch-Engineering-Leiter mit 15 Jahren Erfahrung verantwortet Kerem Feldeinsätze und Retrofit-Integrationen nach IEC-Sicherheitsstandards." },
];

export function getMessages(locale: Locale): SiteMessages { return locale === "de" ? DE : EN; }
export function getProducts(locale: Locale): Product[] { return locale === "de" ? GERMAN_PRODUCTS : PRODUCTS; }
export function getTeamMembers(locale: Locale): TeamMember[] { return locale === "de" ? GERMAN_TEAM : TEAM_MEMBERS; }
export function getServiceStats(locale: Locale): ServiceStat[] { return locale === "de" ? SERVICE_STATS.map((stat, index) => ({ ...stat, label: ["Industriestandorte", "Durchschnittliche Lastspitzenreduktion", "Jährlich vermiedene CO₂-Emissionen", "Plattformverfügbarkeit"][index] })) : SERVICE_STATS; }
export function getFooterLinks(locale: Locale): FooterLinkGroup[] { const messages = getMessages(locale); return [{ title: messages.footer.company, links: [{ label: locale === "de" ? "Über uns" : "About Us", href: "/about" }, { label: messages.footer.careers, href: "/about#careers" }, { label: messages.nav.contact, href: "/contact" }] }, { title: messages.footer.products, links: getProducts(locale).map((product) => ({ label: product.name, href: `/products#${product.id}` })) }, { title: messages.footer.legal, links: [{ label: messages.footer.privacy, href: "/privacy" }, { label: messages.footer.terms, href: "/terms" }, { label: messages.footer.cookies, href: "/cookies" }] }]; }
export { FOOTER_LINKS };
